sonar.projectKey=appointment1_appointment-
sonar.organization=appointment1
sonar.host.url=https://sonarcloud.io

# ========================
# Source Code
# ========================
sonar.sources=src/main/java

# ========================
# Test Code
# ========================
sonar.tests=src/test/java
sonar.test.inclusions=**/*Test.java

# ========================
# Binaries (مهم جدًا لـ Java)
# ========================
sonar.java.binaries=target/classes

# ========================
# Coverage (JaCoCo)
# ========================
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
sonar.java.coveragePlugin=jacoco

# ========================
# Exclusions (نفس اللي في POM)
# ========================
sonar.coverage.exclusions=\

**/Domain_Layer/**,\
**/Persistence_Layer/**,\
**/presentation_Layer/**

# ========================
# Encoding
# ========================
sonar.sourceEncoding=UTF-8
